import type { Metadata } from "next";
import type { RootLayoutParam } from "@/type";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from 'next/headers';
import { Box } from '@chakra-ui/react';
import { Provider } from "@/components/ui/provider"
import "./globals.css";
import { Header } from "../components/ui/header";

type Lang = 'en' | 'zh';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: RootLayoutParam) {
  const locale = (await cookies()).get('lang')?.value || 'en';
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Header locale={locale as Lang} />
          <Box as="main" pt="60px">
            {children}
          </Box>
        </Provider>
      </body>
    </html>
  );
}
